name: Create JIRA Ticket
on:
  issues:
    types: [opened]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Login to JIRA
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Create JIRA Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: ${{ secrets.JIRA_BASE_URL }}
          issuetype: Task
          summary: "GH Issue: ${{ github.event.issue.title }}"
          description: |
            GitHub Issue Link: ${{ github.event.issue.html_url }}
            
            Reporter: ${{ github.event.issue.user.login }}
            
          # fields: '{"customfield_10000": "github-issue", "priority": {"name": "Medium"}}'

      - name: Log created issue
        run: echo "Created issue ${{ steps.create.outputs.issue }}"
